project_name: Predictive_Maintenance_Manual_MLOps
author: Rakesh Kumar Mandal
data_path:
  raw_file: datastore/raw/v1_raw_ai4i2020.csv
  processed_dir: datastore/processed/
  production_dir: datastore/production/
  current_version: v1
processing:
  dev_split: 7000
  production_split: 3000
train:
  test_size: 0.2
  stratify: true
model_params:
  algorithm: RandomForest
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  class_weight: balanced
random_state: 42
deployment:
  model_dir: models/
  current_model: model_v1.pkl
  port: 8000
  host: 0.0.0.0
